from __future__ import annotations

from tests.integration.phase3_runtime_db_assign_child_cases import (
    test_phase3_assign_child_blocks_open_overwrite_and_supersedes_closed_assignment,
    test_phase3_assign_child_rejects_missing_backing_current_artifact_file,
    test_phase3_assign_child_uses_relational_direct_child_authority,
)
from tests.integration.phase3_runtime_db_checkpoint_cases import (
    test_phase3_record_checkpoint_defers_artifact_and_projection_files_until_commit,
    test_phase3_record_checkpoint_rejects_second_terminal_checkpoint_on_open_attempt,
    test_phase3_retry_creates_new_attempt_with_checkpoint_consume_ref,
)
from tests.integration.phase3_runtime_db_prompt_cases import (
    test_phase3_parent_prompt_uses_relational_child_authority_when_shadows_drift,
    test_phase3_rerenders_historical_dispatch_from_dispatch_lineage,
    test_phase3_rerenders_historical_parent_dispatch_without_later_child_checkpoint,
)
from tests.integration.phase3_runtime_db_release_cases import (
    test_phase3_minimal_root_closure_remains_readable,
    test_phase3_parent_worker_flow_and_replan_state,
    test_phase3_release_blocked_requires_current_root_and_whole_flow_blocked_basis,
    test_phase3_release_precondition_is_dispatch_local_not_continuation_state,
)
from tests.integration.phase3_runtime_db_replan_cases import (
    test_phase3_structural_replan_and_assign_child_persist_lineage,
    test_phase3_structural_replan_rebinds_child_assignment_budget_counter,
    test_phase3_structural_replan_rebinds_same_attempt_publication_and_checkpoint_lineage,
    test_phase3_structural_replan_uses_relational_parent_child_authority,
)

__all__ = [
    "test_phase3_assign_child_blocks_open_overwrite_and_supersedes_closed_assignment",
    "test_phase3_assign_child_rejects_missing_backing_current_artifact_file",
    "test_phase3_assign_child_uses_relational_direct_child_authority",
    "test_phase3_minimal_root_closure_remains_readable",
    "test_phase3_parent_prompt_uses_relational_child_authority_when_shadows_drift",
    "test_phase3_parent_worker_flow_and_replan_state",
    "test_phase3_record_checkpoint_defers_artifact_and_projection_files_until_commit",
    "test_phase3_record_checkpoint_rejects_second_terminal_checkpoint_on_open_attempt",
    "test_phase3_release_blocked_requires_current_root_and_whole_flow_blocked_basis",
    "test_phase3_release_precondition_is_dispatch_local_not_continuation_state",
    "test_phase3_rerenders_historical_dispatch_from_dispatch_lineage",
    "test_phase3_rerenders_historical_parent_dispatch_without_later_child_checkpoint",
    "test_phase3_retry_creates_new_attempt_with_checkpoint_consume_ref",
    "test_phase3_structural_replan_and_assign_child_persist_lineage",
    "test_phase3_structural_replan_rebinds_child_assignment_budget_counter",
    "test_phase3_structural_replan_rebinds_same_attempt_publication_and_checkpoint_lineage",
    "test_phase3_structural_replan_uses_relational_parent_child_authority",
]
