# ruff: noqa: F401

from tests.integration.runtime_schema_contract_database_tests import (
    test_runtime_schema_emits_columns_and_constraints_for_phase3_currentness,
    test_runtime_schema_emits_definition_plan_and_task_lineage_foreign_keys,
    test_runtime_schema_emits_flow_assignment_and_dispatch_lineage_foreign_keys,
    test_runtime_schema_emits_indexes_and_removes_legacy_release_flags,
)
from tests.integration.runtime_schema_contract_guard_tests import (
    test_runtime_schema_rejects_cross_scope_parent_flow_node_ids,
    test_runtime_schema_rejects_cross_scope_parent_flow_revision_ids,
    test_runtime_schema_rejects_dispatch_attempt_from_another_assignment,
    test_runtime_schema_rejects_dispatch_flow_node_from_another_revision,
    test_runtime_schema_rejects_dispatch_flow_revision_from_another_flow,
    test_runtime_schema_rejects_mismatched_artifact_publication_flow_node_ids,
    test_runtime_schema_rejects_mismatched_callback_binding_dispatch_tuple,
    test_runtime_schema_rejects_mismatched_checkpoint_flow_node_ids,
)
from tests.integration.runtime_schema_contract_model_tests import (
    test_observability_file_refs_infer_support_kinds_from_projection_paths,
    test_operator_support_surface_refs_emit_explicit_kinds_for_operator_carriers,
    test_operator_support_surface_refs_reject_conflicting_fixed_kinds,
    test_parent_tool_call_uses_tool_name_to_validate_payload_shape,
    test_runtime_mapper_exposes_currentness_chain_and_dispatch_sidecars,
)
