"""Temporary Phase 6 shims for the legacy runtime owners."""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

from autoclaw.schemas.runtime.contracts import (
    PROMPT_FAMILY_NODE_KINDS,
    AssignmentConsumeRef,
    AssignmentProjection,
    CheckpointHandoff,
    CheckpointKind,
    CheckpointOutcome,
    CheckpointProjection,
    DispatchDeliveryStatus,
    EgressBoundary,
    EvidenceKind,
    EvidenceRef,
    FlowStatus,
    ManifestCurrentContextProjection,
    ManifestDependencyProjection,
    ManifestFilesystemRootsProjection,
    ManifestNodeConsumeProjection,
    ManifestNodeCriteriaProjection,
    ManifestNodeProduceProjection,
    ManifestNodeProjection,
    ManifestProjection,
    ManifestTaskProjection,
    ManifestWorkflowProjection,
    NodeKind,
    NodeRuntimeFileKind,
    NodeRuntimeFileRef,
    ParentRootToolName,
    PersistedPromptRecord,
    ProduceRequirement,
    PromptFamily,
    PromptRenderRequest,
    PromptSendMode,
    PromptTransportRequest,
    RenderedPromptBundle,
    ResolvedNodeContext,
    RuntimeBootstrapProjectionInput,
    RuntimeBootstrapResult,
    RuntimeContextRef,
    RuntimeLaunchInput,
    RuntimeText,
    SlotIdentifier,
    StructuralEditPaletteProjection,
    StructuralEditPolicyProjection,
    StructuralEditRoleProjection,
    TaskComposeInput,
    TaskComposeRootsInput,
    TaskComposeTaskInput,
    TaskComposeWorkflowInput,
    TaskIdentifier,
    TaskRootBindingInput,
    TaskRootMode,
    TaskRootPaths,
    prompt_family_for_node_kind,
    validate_prompt_family_for_node_kind,
    validate_prompt_render_request,
)

if TYPE_CHECKING:
    from autoclaw.runtime.control import (
        accept_boundary,
        call_parent_tool,
        cancel_runtime_flow,
        continue_runtime_flow,
        list_runtime_flows,
        observability_ref,
        operator_snapshot,
        operator_trace,
        pause_runtime_flow,
        record_checkpoint,
        runtime_flow_read,
    )
    from autoclaw.runtime.launch import launch_task_runtime
    from autoclaw.runtime.prompt import render_prompt_bundle
    from autoclaw.runtime.task_root import localize_external_resource, resolve_task_root_paths

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "accept_boundary": ("app.runtime.control.boundary.service", "accept_boundary"),
    "call_parent_tool": ("app.runtime.control.parent_tools", "call_parent_tool"),
    "cancel_runtime_flow": ("app.runtime.control.flow.service", "cancel_runtime_flow"),
    "continue_runtime_flow": ("app.runtime.control.flow.service", "continue_runtime_flow"),
    "launch_task_runtime": ("app.runtime.launch.service", "launch_task_runtime"),
    "list_runtime_flows": ("app.runtime.control.flow.service", "list_runtime_flows"),
    "localize_external_resource": ("app.runtime.task_root", "localize_external_resource"),
    "observability_ref": ("app.runtime.control.observability", "observability_ref"),
    "operator_snapshot": ("app.runtime.control.observability", "operator_snapshot"),
    "operator_trace": ("app.runtime.control.observability", "operator_trace"),
    "pause_runtime_flow": ("app.runtime.control.flow.service", "pause_runtime_flow"),
    "record_checkpoint": ("app.runtime.control.checkpoint.recording", "record_checkpoint"),
    "render_prompt_bundle": ("app.runtime.prompt.bundle", "render_prompt_bundle"),
    "resolve_task_root_paths": ("app.runtime.task_root", "resolve_task_root_paths"),
    "runtime_flow_read": ("app.runtime.control.flow.service", "runtime_flow_read"),
}


def __getattr__(name: str) -> Any:
    module_name, attribute_name = _LAZY_EXPORTS.get(name, (None, None))
    if module_name is None or attribute_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name), attribute_name)
    globals()[name] = value
    return value


__all__ = [
    "PROMPT_FAMILY_NODE_KINDS",
    "AssignmentConsumeRef",
    "AssignmentProjection",
    "CheckpointHandoff",
    "CheckpointKind",
    "CheckpointOutcome",
    "CheckpointProjection",
    "DispatchDeliveryStatus",
    "EgressBoundary",
    "EvidenceKind",
    "EvidenceRef",
    "FlowStatus",
    "ManifestCurrentContextProjection",
    "ManifestDependencyProjection",
    "ManifestFilesystemRootsProjection",
    "ManifestNodeConsumeProjection",
    "ManifestNodeCriteriaProjection",
    "ManifestNodeProduceProjection",
    "ManifestNodeProjection",
    "ManifestProjection",
    "ManifestTaskProjection",
    "ManifestWorkflowProjection",
    "NodeKind",
    "NodeRuntimeFileKind",
    "NodeRuntimeFileRef",
    "ParentRootToolName",
    "PersistedPromptRecord",
    "ProduceRequirement",
    "PromptFamily",
    "PromptRenderRequest",
    "PromptSendMode",
    "PromptTransportRequest",
    "RenderedPromptBundle",
    "ResolvedNodeContext",
    "RuntimeBootstrapProjectionInput",
    "RuntimeBootstrapResult",
    "RuntimeContextRef",
    "RuntimeLaunchInput",
    "RuntimeText",
    "SlotIdentifier",
    "StructuralEditPaletteProjection",
    "StructuralEditPolicyProjection",
    "StructuralEditRoleProjection",
    "TaskComposeInput",
    "TaskComposeRootsInput",
    "TaskComposeTaskInput",
    "TaskComposeWorkflowInput",
    "TaskIdentifier",
    "TaskRootBindingInput",
    "TaskRootMode",
    "TaskRootPaths",
    "accept_boundary",
    "call_parent_tool",
    "cancel_runtime_flow",
    "continue_runtime_flow",
    "launch_task_runtime",
    "list_runtime_flows",
    "localize_external_resource",
    "observability_ref",
    "operator_snapshot",
    "operator_trace",
    "pause_runtime_flow",
    "prompt_family_for_node_kind",
    "record_checkpoint",
    "render_prompt_bundle",
    "resolve_task_root_paths",
    "runtime_flow_read",
    "validate_prompt_family_for_node_kind",
    "validate_prompt_render_request",
]
