"""Runtime-facing shell over the OpenClaw gateway substrate."""

from __future__ import annotations

import autoclaw.integrations.openclaw.gateway.host_setup as _owner

AUTOCLAW_NODE_MCP_SERVER_NAME = _owner.AUTOCLAW_NODE_MCP_SERVER_NAME
AUTOCLAW_OPERATOR_AGENT_ID = _owner.AUTOCLAW_OPERATOR_AGENT_ID
AUTOCLAW_OPERATOR_MCP_SERVER_NAME = _owner.AUTOCLAW_OPERATOR_MCP_SERVER_NAME
AUTOCLAW_WORKER_AGENT_ID = _owner.AUTOCLAW_WORKER_AGENT_ID
OPENCLAW_DEFAULT_AGENT_ID = _owner.OPENCLAW_DEFAULT_AGENT_ID
WORKER_OPERATOR_TOOL_DENY = _owner.WORKER_OPERATOR_TOOL_DENY
WORKER_RUNTIME_TOOL_DENY = _owner.WORKER_RUNTIME_TOOL_DENY
OpenClawAgentSummary = _owner.OpenClawAgentSummary
bootstrap_openclaw_agent = _owner.bootstrap_openclaw_agent
build_autoclaw_agent_entries = _owner.build_autoclaw_agent_entries
build_autoclaw_mcp_servers = _owner.build_autoclaw_mcp_servers
default_openclaw_agent_workspace = _owner.default_openclaw_agent_workspace
gateway_bootstrap_needed = _owner.gateway_bootstrap_needed
host_base_url_from_config = _owner.host_base_url_from_config
list_openclaw_agents = _owner.list_openclaw_agents
load_host_agent_entries_from_config = _owner.load_host_agent_entries_from_config
load_host_agents_from_config = _owner.load_host_agents_from_config
load_host_mcp_servers_from_config = _owner.load_host_mcp_servers_from_config
patch_openclaw_gateway_settings = _owner.patch_openclaw_gateway_settings
resolved_gateway_bootstrap_values = _owner.resolved_gateway_bootstrap_values
run_openclaw_cli = _owner.run_openclaw_cli
set_openclaw_agent_profiles = _owner.set_openclaw_agent_profiles
set_openclaw_mcp_servers = _owner.set_openclaw_mcp_servers
