"""Temporary Phase 6 shims for the legacy definition-schema owner."""

from __future__ import annotations

from autoclaw.schemas.definitions.registry import (
    BudgetSpec,
    DefinitionContent,
    DefinitionHistorySort,
    DefinitionKind,
    DefinitionListQuery,
    DefinitionListSort,
    DefinitionRevisionDetailResponse,
    DefinitionRevisionHistoryEntry,
    DefinitionRevisionHistoryQuery,
    DefinitionRevisionHistoryResponse,
    DefinitionSummaryListResponse,
    DefinitionSummaryRead,
    DefinitionUploadRequest,
    PolicyDefinitionFile,
    PolicyDefinitionInput,
    RoleDefinitionFile,
    RoleDefinitionInput,
)
from autoclaw.schemas.definitions.validation import FlattenedNode, validate_workflow_definition
from autoclaw.schemas.definitions.workflow import (
    ChildDefaults,
    ConsumeBuckets,
    ConsumeSelector,
    CriteriaDeclaration,
    NodeDefinitionInput,
    NodeKind,
    NonEmptyText,
    ProduceBuckets,
    ProduceSlot,
    RootNodeDefinition,
    SlotIdentifier,
    WorkflowDefinitionFile,
    WorkflowDefinitionInput,
    WorkflowIdentifier,
    WorkflowNode,
)

__all__ = [
    "BudgetSpec",
    "ChildDefaults",
    "ConsumeBuckets",
    "ConsumeSelector",
    "CriteriaDeclaration",
    "DefinitionContent",
    "DefinitionHistorySort",
    "DefinitionKind",
    "DefinitionListQuery",
    "DefinitionListSort",
    "DefinitionRevisionDetailResponse",
    "DefinitionRevisionHistoryEntry",
    "DefinitionRevisionHistoryQuery",
    "DefinitionRevisionHistoryResponse",
    "DefinitionSummaryListResponse",
    "DefinitionSummaryRead",
    "DefinitionUploadRequest",
    "FlattenedNode",
    "NodeDefinitionInput",
    "NodeKind",
    "NonEmptyText",
    "PolicyDefinitionFile",
    "PolicyDefinitionInput",
    "ProduceBuckets",
    "ProduceSlot",
    "RoleDefinitionFile",
    "RoleDefinitionInput",
    "RootNodeDefinition",
    "SlotIdentifier",
    "WorkflowDefinitionFile",
    "WorkflowDefinitionInput",
    "WorkflowIdentifier",
    "WorkflowNode",
    "validate_workflow_definition",
]
