"""fresh initial schema"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "20260414_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "policy_definitions",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_definitions")),
    )
    op.create_index(op.f("ix_policy_definitions_key"), "policy_definitions", ["key"], unique=True)
    op.create_table(
        "role_definitions",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_definitions")),
    )
    op.create_index(op.f("ix_role_definitions_key"), "role_definitions", ["key"], unique=True)
    op.create_table(
        "skill_registry",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("openclaw", "local", "remote", name="skill_provider"),
            nullable=False,
        ),
        sa.Column("source_uri", sa.String(length=512), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_registry")),
    )
    op.create_index(op.f("ix_skill_registry_key"), "skill_registry", ["key"], unique=True)
    op.create_table(
        "tasks",
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "blocked",
                "failed",
                "succeeded",
                "cancelled",
                name="task_status",
            ),
            nullable=False,
        ),
        sa.Column("input_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_table(
        "workflow_definitions",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_definitions")),
    )
    op.create_index(
        op.f("ix_workflow_definitions_key"), "workflow_definitions", ["key"], unique=True
    )
    op.create_table(
        "policy_versions",
        sa.Column("policy_definition_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "published", "archived", name="definition_version_status"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["policy_definition_id"],
            ["policy_definitions.id"],
            name=op.f("fk_policy_versions_policy_definition_id_policy_definitions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_versions")),
        sa.UniqueConstraint(
            "policy_definition_id", "version", name="uq_policy_versions_definition_version"
        ),
    )
    op.create_index(
        "ix_policy_versions_definition_status_version",
        "policy_versions",
        ["policy_definition_id", "status", "version"],
        unique=False,
    )
    op.create_table(
        "role_versions",
        sa.Column("role_definition_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "published", "archived", name="definition_version_status"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_definition_id"],
            ["role_definitions.id"],
            name=op.f("fk_role_versions_role_definition_id_role_definitions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_versions")),
        sa.UniqueConstraint(
            "role_definition_id", "version", name="uq_role_versions_definition_version"
        ),
    )
    op.create_index(
        "ix_role_versions_definition_status_version",
        "role_versions",
        ["role_definition_id", "status", "version"],
        unique=False,
    )
    op.create_table(
        "skill_versions",
        sa.Column("skill_registry_id", sa.Uuid(), nullable=False),
        sa.Column("version_label", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "published", "archived", name="definition_version_status"),
            nullable=False,
        ),
        sa.Column("source_ref", sa.String(length=256), nullable=True),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_registry_id"],
            ["skill_registry.id"],
            name=op.f("fk_skill_versions_skill_registry_id_skill_registry"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_versions")),
        sa.UniqueConstraint(
            "skill_registry_id", "version_label", name="uq_skill_versions_registry_version"
        ),
    )
    op.create_index(
        "ix_skill_versions_registry_status",
        "skill_versions",
        ["skill_registry_id", "status"],
        unique=False,
    )
    op.create_table(
        "workflow_versions",
        sa.Column("workflow_definition_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "published", "archived", name="definition_version_status"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_definition_id"],
            ["workflow_definitions.id"],
            name=op.f("fk_workflow_versions_workflow_definition_id_workflow_definitions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_versions")),
        sa.UniqueConstraint(
            "workflow_definition_id", "version", name="uq_workflow_versions_definition_version"
        ),
    )
    op.create_index(
        "ix_workflow_versions_definition_status_version",
        "workflow_versions",
        ["workflow_definition_id", "status", "version"],
        unique=False,
    )
    op.create_table(
        "compiled_plans",
        sa.Column("workflow_version_id", sa.Uuid(), nullable=False),
        sa.Column("compiler_version", sa.String(length=64), nullable=False),
        sa.Column("plan_hash", sa.String(length=128), nullable=False),
        sa.Column("source_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_version_id"],
            ["workflow_versions.id"],
            name=op.f("fk_compiled_plans_workflow_version_id_workflow_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_compiled_plans")),
    )
    op.create_index(
        op.f("ix_compiled_plans_plan_hash"), "compiled_plans", ["plan_hash"], unique=True
    )
    op.create_table(
        "compiled_plan_edges",
        sa.Column("compiled_plan_id", sa.Uuid(), nullable=False),
        sa.Column("from_node_key", sa.String(length=128), nullable=False),
        sa.Column("to_node_key", sa.String(length=128), nullable=False),
        sa.Column(
            "edge_kind", sa.Enum("control", "dependency", name="flow_edge_kind"), nullable=False
        ),
        sa.Column("condition_expr", sa.Text(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["compiled_plan_id"],
            ["compiled_plans.id"],
            name=op.f("fk_compiled_plan_edges_compiled_plan_id_compiled_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_compiled_plan_edges")),
    )
    op.create_index(
        "ix_compiled_plan_edges_plan_order",
        "compiled_plan_edges",
        ["compiled_plan_id", "order_index"],
        unique=False,
    )
    op.create_table(
        "compiled_plan_nodes",
        sa.Column("compiled_plan_id", sa.Uuid(), nullable=False),
        sa.Column("node_key", sa.String(length=128), nullable=False),
        sa.Column("parent_node_key", sa.String(length=128), nullable=True),
        sa.Column("role_version_id", sa.Uuid(), nullable=True),
        sa.Column("policy_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "mode",
            sa.Enum(
                "plan",
                "persistent_execute",
                "review",
                "wait",
                "pause",
                "sync",
                name="workflow_mode",
            ),
            nullable=False,
        ),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("skill_bindings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["compiled_plan_id"],
            ["compiled_plans.id"],
            name=op.f("fk_compiled_plan_nodes_compiled_plan_id_compiled_plans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id"],
            ["policy_versions.id"],
            name=op.f("fk_compiled_plan_nodes_policy_version_id_policy_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["role_version_id"],
            ["role_versions.id"],
            name=op.f("fk_compiled_plan_nodes_role_version_id_role_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_compiled_plan_nodes")),
        sa.UniqueConstraint(
            "compiled_plan_id", "node_key", name="uq_compiled_plan_nodes_plan_node_key"
        ),
    )
    op.create_index(
        "ix_compiled_plan_nodes_plan_order",
        "compiled_plan_nodes",
        ["compiled_plan_id", "order_index"],
        unique=False,
    )
    op.create_table(
        "flows",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("seed_compiled_plan_id", sa.Uuid(), nullable=False),
        sa.Column("active_flow_revision_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "blocked",
                "paused",
                "failed",
                "succeeded",
                "cancelled",
                name="flow_status",
            ),
            nullable=False,
        ),
        sa.Column("execution_no", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["seed_compiled_plan_id"],
            ["compiled_plans.id"],
            name=op.f("fk_flows_seed_compiled_plan_id_compiled_plans"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_flows_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flows")),
    )
    op.create_index(
        "ix_flows_active_flow_revision_id", "flows", ["active_flow_revision_id"], unique=False
    )
    op.create_index("ix_flows_task_status", "flows", ["task_id", "status"], unique=False)
    op.create_table(
        "flow_revisions",
        sa.Column("flow_id", sa.Uuid(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("compiled_plan_id", sa.Uuid(), nullable=False),
        sa.Column("parent_flow_revision_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("candidate", "active", "retired", "aborted", name="flow_revision_status"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("source_patch_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("adopted_from_node_plan_revision_id", sa.Uuid(), nullable=True),
        sa.Column("adopted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["compiled_plan_id"],
            ["compiled_plans.id"],
            name=op.f("fk_flow_revisions_compiled_plan_id_compiled_plans"),
        ),
        sa.ForeignKeyConstraint(
            ["flow_id"],
            ["flows.id"],
            name=op.f("fk_flow_revisions_flow_id_flows"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_flow_revision_id"],
            ["flow_revisions.id"],
            name=op.f("fk_flow_revisions_parent_flow_revision_id_flow_revisions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flow_revisions")),
        sa.UniqueConstraint("flow_id", "revision_no", name="uq_flow_revisions_flow_revision_no"),
    )
    op.create_table(
        "flow_nodes",
        sa.Column("flow_id", sa.Uuid(), nullable=False),
        sa.Column("flow_revision_id", sa.Uuid(), nullable=False),
        sa.Column("source_compiled_plan_node_id", sa.Uuid(), nullable=True),
        sa.Column("parent_flow_node_id", sa.Uuid(), nullable=True),
        sa.Column("node_key", sa.String(length=128), nullable=False),
        sa.Column("node_path", sa.String(length=256), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "ready", "running", "waiting", "paused", "done", "failed", name="flow_node_state"
            ),
            nullable=False,
        ),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("status_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["flow_id"], ["flows.id"], name=op.f("fk_flow_nodes_flow_id_flows"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["flow_revision_id"],
            ["flow_revisions.id"],
            name=op.f("fk_flow_nodes_flow_revision_id_flow_revisions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_flow_node_id"],
            ["flow_nodes.id"],
            name=op.f("fk_flow_nodes_parent_flow_node_id_flow_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["source_compiled_plan_node_id"],
            ["compiled_plan_nodes.id"],
            name=op.f("fk_flow_nodes_source_compiled_plan_node_id_compiled_plan_nodes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flow_nodes")),
        sa.UniqueConstraint("flow_revision_id", "node_key", name="uq_flow_nodes_revision_node_key"),
    )
    op.create_index(
        "ix_flow_nodes_flow_revision_order",
        "flow_nodes",
        ["flow_id", "flow_revision_id", "order_index"],
        unique=False,
    )
    op.create_table(
        "flow_edges",
        sa.Column("flow_id", sa.Uuid(), nullable=False),
        sa.Column("flow_revision_id", sa.Uuid(), nullable=False),
        sa.Column("from_flow_node_id", sa.Uuid(), nullable=False),
        sa.Column("to_flow_node_id", sa.Uuid(), nullable=False),
        sa.Column(
            "edge_kind", sa.Enum("control", "dependency", name="flow_edge_kind"), nullable=False
        ),
        sa.Column("condition_expr", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["flow_id"], ["flows.id"], name=op.f("fk_flow_edges_flow_id_flows"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["flow_revision_id"],
            ["flow_revisions.id"],
            name=op.f("fk_flow_edges_flow_revision_id_flow_revisions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["from_flow_node_id"],
            ["flow_nodes.id"],
            name=op.f("fk_flow_edges_from_flow_node_id_flow_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_flow_node_id"],
            ["flow_nodes.id"],
            name=op.f("fk_flow_edges_to_flow_node_id_flow_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flow_edges")),
    )
    op.create_index(
        "ix_flow_edges_flow_revision_id",
        "flow_edges",
        ["flow_id", "flow_revision_id"],
        unique=False,
    )
    op.create_table(
        "node_attempts",
        sa.Column("flow_id", sa.Uuid(), nullable=False),
        sa.Column("flow_revision_id", sa.Uuid(), nullable=False),
        sa.Column("flow_node_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "blocked",
                "failed",
                "succeeded",
                "cancelled",
                "aborted",
                name="node_attempt_status",
            ),
            nullable=False,
        ),
        sa.Column("retry_of_node_attempt_id", sa.Uuid(), nullable=True),
        sa.Column("failure_signature", sa.String(length=256), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["flow_id"],
            ["flows.id"],
            name=op.f("fk_node_attempts_flow_id_flows"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flow_node_id"],
            ["flow_nodes.id"],
            name=op.f("fk_node_attempts_flow_node_id_flow_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flow_revision_id"],
            ["flow_revisions.id"],
            name=op.f("fk_node_attempts_flow_revision_id_flow_revisions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["retry_of_node_attempt_id"],
            ["node_attempts.id"],
            name=op.f("fk_node_attempts_retry_of_node_attempt_id_node_attempts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_attempts")),
        sa.UniqueConstraint("flow_node_id", "number", name="uq_node_attempts_node_number"),
    )
    op.create_index(
        "ix_node_attempts_flow_node_number",
        "node_attempts",
        ["flow_id", "flow_node_id", "number"],
        unique=False,
    )
    op.create_table(
        "approvals",
        sa.Column("flow_id", sa.Uuid(), nullable=False),
        sa.Column("flow_node_id", sa.Uuid(), nullable=True),
        sa.Column("node_attempt_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "not_required", "pending", "approved", "rejected", "expired", name="approval_status"
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("request_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resolution_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["flow_id"], ["flows.id"], name=op.f("fk_approvals_flow_id_flows"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["flow_node_id"], ["flow_nodes.id"], name=op.f("fk_approvals_flow_node_id_flow_nodes")
        ),
        sa.ForeignKeyConstraint(
            ["node_attempt_id"],
            ["node_attempts.id"],
            name=op.f("fk_approvals_node_attempt_id_node_attempts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index("ix_approvals_flow_status", "approvals", ["flow_id", "status"], unique=False)
    op.create_table(
        "node_checkpoints",
        sa.Column("flow_id", sa.Uuid(), nullable=False),
        sa.Column("flow_node_id", sa.Uuid(), nullable=False),
        sa.Column("node_attempt_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("green", "retry", "blocked", "needs_approval", name="checkpoint_status"),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("failure_signature", sa.String(length=256), nullable=True),
        sa.Column("recommended_next_action", sa.String(length=128), nullable=True),
        sa.Column(
            "wait_reason",
            sa.Enum(
                "approval", "dependency", "watchdog", "operator", "context", name="wait_reason"
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["flow_id"],
            ["flows.id"],
            name=op.f("fk_node_checkpoints_flow_id_flows"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flow_node_id"],
            ["flow_nodes.id"],
            name=op.f("fk_node_checkpoints_flow_node_id_flow_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["node_attempt_id"],
            ["node_attempts.id"],
            name=op.f("fk_node_checkpoints_node_attempt_id_node_attempts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_checkpoints")),
        sa.UniqueConstraint(
            "node_attempt_id", "sequence_no", name="uq_node_checkpoints_attempt_sequence"
        ),
    )
    op.create_index(
        "ix_node_checkpoints_flow_attempt",
        "node_checkpoints",
        ["flow_id", "node_attempt_id"],
        unique=False,
    )
    op.create_table(
        "node_sessions",
        sa.Column("flow_id", sa.Uuid(), nullable=False),
        sa.Column("flow_node_id", sa.Uuid(), nullable=False),
        sa.Column("node_attempt_id", sa.Uuid(), nullable=True),
        sa.Column("provider_session_key", sa.String(length=128), nullable=False),
        sa.Column(
            "status", sa.Enum("idle", "active", "ended", name="node_session_status"), nullable=False
        ),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["flow_id"],
            ["flows.id"],
            name=op.f("fk_node_sessions_flow_id_flows"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flow_node_id"],
            ["flow_nodes.id"],
            name=op.f("fk_node_sessions_flow_node_id_flow_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["node_attempt_id"],
            ["node_attempts.id"],
            name=op.f("fk_node_sessions_node_attempt_id_node_attempts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_sessions")),
        sa.UniqueConstraint("flow_node_id", name="uq_node_sessions_flow_node_id"),
    )
    op.create_table(
        "context_items",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("flow_id", sa.Uuid(), nullable=True),
        sa.Column("flow_revision_id", sa.Uuid(), nullable=True),
        sa.Column("flow_node_id", sa.Uuid(), nullable=True),
        sa.Column("node_attempt_id", sa.Uuid(), nullable=True),
        sa.Column(
            "scope",
            sa.Enum(
                "task_shared",
                "flow_shared",
                "node_private",
                "attempt_scratch",
                name="context_item_scope",
            ),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "fact",
                "decision",
                "summary",
                "suggestion",
                "note",
                "artifact",
                "log",
                name="context_item_kind",
            ),
            nullable=False,
        ),
        sa.Column("visibility_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "published", "superseded", "archived", name="context_item_status"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("storage_uri", sa.String(length=512), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("published_by", sa.String(length=128), nullable=False),
        sa.Column("source_checkpoint_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["flow_id"], ["flows.id"], name=op.f("fk_context_items_flow_id_flows")
        ),
        sa.ForeignKeyConstraint(
            ["flow_node_id"],
            ["flow_nodes.id"],
            name=op.f("fk_context_items_flow_node_id_flow_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["flow_revision_id"],
            ["flow_revisions.id"],
            name=op.f("fk_context_items_flow_revision_id_flow_revisions"),
        ),
        sa.ForeignKeyConstraint(
            ["node_attempt_id"],
            ["node_attempts.id"],
            name=op.f("fk_context_items_node_attempt_id_node_attempts"),
        ),
        sa.ForeignKeyConstraint(
            ["source_checkpoint_id"],
            ["node_checkpoints.id"],
            name=op.f("fk_context_items_source_checkpoint_id_node_checkpoints"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_context_items_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_context_items")),
    )
    op.create_index(
        "ix_context_items_scope_status",
        "context_items",
        ["task_id", "scope", "status"],
        unique=False,
    )
    op.create_table(
        "context_manifests",
        sa.Column("flow_id", sa.Uuid(), nullable=False),
        sa.Column("flow_node_id", sa.Uuid(), nullable=False),
        sa.Column("node_attempt_id", sa.Uuid(), nullable=False),
        sa.Column("node_session_id", sa.Uuid(), nullable=True),
        sa.Column("manifest_no", sa.Integer(), nullable=False),
        sa.Column("manifest_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("manifest_hash", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum("projected", "acked", "superseded", name="context_manifest_status"),
            nullable=False,
        ),
        sa.Column("projected_at", sa.DateTime(), nullable=False),
        sa.Column("acked_at", sa.DateTime(), nullable=True),
        sa.Column("ack_checkpoint_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["ack_checkpoint_id"],
            ["node_checkpoints.id"],
            name=op.f("fk_context_manifests_ack_checkpoint_id_node_checkpoints"),
        ),
        sa.ForeignKeyConstraint(
            ["flow_id"],
            ["flows.id"],
            name=op.f("fk_context_manifests_flow_id_flows"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flow_node_id"],
            ["flow_nodes.id"],
            name=op.f("fk_context_manifests_flow_node_id_flow_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["node_attempt_id"],
            ["node_attempts.id"],
            name=op.f("fk_context_manifests_node_attempt_id_node_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["node_session_id"],
            ["node_sessions.id"],
            name=op.f("fk_context_manifests_node_session_id_node_sessions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_context_manifests")),
        sa.UniqueConstraint(
            "node_attempt_id", "manifest_no", name="uq_context_manifests_attempt_manifest_no"
        ),
    )
    op.create_index(
        "ix_context_manifests_flow_status", "context_manifests", ["flow_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_context_manifests_flow_status", table_name="context_manifests")
    op.drop_table("context_manifests")
    op.drop_index("ix_context_items_scope_status", table_name="context_items")
    op.drop_table("context_items")
    op.drop_table("node_sessions")
    op.drop_index("ix_node_checkpoints_flow_attempt", table_name="node_checkpoints")
    op.drop_table("node_checkpoints")
    op.drop_index("ix_approvals_flow_status", table_name="approvals")
    op.drop_table("approvals")
    op.drop_index("ix_node_attempts_flow_node_number", table_name="node_attempts")
    op.drop_table("node_attempts")
    op.drop_index("ix_flow_edges_flow_revision_id", table_name="flow_edges")
    op.drop_table("flow_edges")
    op.drop_index("ix_flow_nodes_flow_revision_order", table_name="flow_nodes")
    op.drop_table("flow_nodes")
    op.drop_table("flow_revisions")
    op.drop_index("ix_flows_task_status", table_name="flows")
    op.drop_index("ix_flows_active_flow_revision_id", table_name="flows")
    op.drop_table("flows")
    op.drop_index("ix_compiled_plan_nodes_plan_order", table_name="compiled_plan_nodes")
    op.drop_table("compiled_plan_nodes")
    op.drop_index("ix_compiled_plan_edges_plan_order", table_name="compiled_plan_edges")
    op.drop_table("compiled_plan_edges")
    op.drop_index(op.f("ix_compiled_plans_plan_hash"), table_name="compiled_plans")
    op.drop_table("compiled_plans")
    op.drop_index("ix_workflow_versions_definition_status_version", table_name="workflow_versions")
    op.drop_table("workflow_versions")
    op.drop_index("ix_skill_versions_registry_status", table_name="skill_versions")
    op.drop_table("skill_versions")
    op.drop_index("ix_role_versions_definition_status_version", table_name="role_versions")
    op.drop_table("role_versions")
    op.drop_index("ix_policy_versions_definition_status_version", table_name="policy_versions")
    op.drop_table("policy_versions")
    op.drop_index(op.f("ix_workflow_definitions_key"), table_name="workflow_definitions")
    op.drop_table("workflow_definitions")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_skill_registry_key"), table_name="skill_registry")
    op.drop_table("skill_registry")
    op.drop_index(op.f("ix_role_definitions_key"), table_name="role_definitions")
    op.drop_table("role_definitions")
    op.drop_index(op.f("ix_policy_definitions_key"), table_name="policy_definitions")
    op.drop_table("policy_definitions")
    # ### end Alembic commands ###
